import os
import time
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")
time.sleep(4)
os.startfile("Youtube-Music-Bot.exe")