from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.proxy import Proxy, ProxyType
from selenium.webdriver.chrome.options import Options
import time
views = int=1000000
view_time = float=224
prox = Proxy()
prox.proxy_type = ProxyType.MANUAL
prox.http_proxy = "p.webshare.io:19999"
prox.socks5_proxy = "p.webshare.io:9999"
prox.ssl_proxy = "p.webshare.io:19999"

capabilities = webdriver.DesiredCapabilities.CHROME
prox.add_to_capabilities(capabilities)
opts1 = Options()
opts1.add_argument('--user-agent=[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36]')
opts1.add_argument('--mute-audio')
opts1.add_argument('--incognito')
opts1.add_argument('--headless')

browser1 = webdriver.Chrome(options=opts1, desired_capabilities=capabilities)
#browser2 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser3 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser4 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser5 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser6 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser7 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser8 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser9 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser10 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser11 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser12 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser13 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser14 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser15 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser16 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser17 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser18 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser19 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser20 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser21 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser22 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser23 = webdriver.ChromeOptions(desired_capabilities=capabilities)
#browser24 = webdriver.ChromeOptions(desired_capabilities=capabilities)

# put video link in ''
for i in range(views):
    browser1.get('')
    play_music_1 = browser1.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
    play_music_1.click()
 #   browser2.get('')
 #   play_music_2 = browser2.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_2.click()
 #   browser3.get('')
 #   play_music_3 = browser3.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_3.click()
 #   browser4.get('')
 #   play_music_4 = browser4.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_4.click()
 #   browser5.get('')
 #   play_music_5 = browser5.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_5.click()
 #   browser6.get('')
 #   play_music_6 = browser6.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_6.click()
 #   browser7.get('')
 #   play_music_7 = browser7.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_7.click()
 #   browser8.get('')
 #   play_music_8 = browser8.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_8.click()
 #   browser9.get('')
 #   play_music_9 = browser9.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_9.click()
 #   browser10.get('')
 #   play_music_10 = browser10.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_10.click()
 #   browser11.get('')
 #   play_music_11 = browser11.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_11.click()
 #   browser6.get('')
 #   play_music_12 = browser12.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_12.click()
 #   browser13.get('')
 #   play_music_13 = browser13.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_13.click()
 #   browser14.get('')
 #   play_music_14 = browser14.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_14.click()
 #   browser15.get('')
 #   play_music_15 = browser15.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_15.click()
 #   browser16.get('')
 #   play_music_16 = browser16.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_16.click()
 #   browser17.get('')
 #   play_music_17 = browser17.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_17.click()
 #   browser18.get('')
 #   play_music_18 = browser18.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_18.click()
 #   browser19.get('')
 #   play_music_19 = browser19.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_19.click()
 #   browser20.get('')
 #   play_music_20 = browser20.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_20.click()
 #   browser21.get('')
 #   play_music_21 = browser21.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_21.click()
 #   browser22.get('')
 #   play_music_22 = browser22.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_22.click()
 #   browser23.get('')
 #   play_music_23 = browser23.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_23.click()
 #   browser24.get('')
 #   play_music_24 = browser24.find_element_by_xpath(""" //*[@id="contents"]/yt-button-renderer/a """)
 #   play_music_24.click()
    time.sleep(view_time)

browser1.close()
#browser2.close()
#browser3.close()
#browser4.close()
#browser5.close()
#browser6.close()
#browser7.close()
#browser8.close()
#browser9.close()
#browser10.close()
#browser11.close()
#browser12.close()
#browser13.close()
#browser14.close()
#browser15.close()
#browser16.close()
#browser17.close()
#browser18.close()
#browser19.close()
#browser20.close()
#browser21.close()
#browser22.close()
#browser23.close()
#browser24.close()


# script by thisisawesome1994